import { type ReactNode, type ElementType } from 'react';
import { Link } from 'wouter';
import { ArrowRight, Check, Clock3, FileText, Info, Loader2, RefreshCw, Sparkles, UploadCloud } from 'lucide-react';

export function Skeleton({ className = '' }: { className?: string }) { return <div className={`skeleton rounded-lg ${className}`} />; }
export function LoadingBlock() { return <div className="space-y-5"><Skeleton className="h-8 w-48" /><Skeleton className="h-24 w-full" /><div className="grid gap-4 sm:grid-cols-2"><Skeleton className="h-40" /><Skeleton className="h-40" /></div></div>; }
export function ErrorState({ onRetry }: { onRetry?: () => void }) { return <div className="flex min-h-[280px] flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-card text-center"><Info size={25} className="mb-3 text-destructive" /><p className="font-display text-lg font-bold">We couldn't load that just now</p><p className="mt-1 text-sm text-muted-foreground">Your information is safe. Try again in a moment.</p>{onRetry && <button onClick={onRetry} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-primary-foreground" data-testid="button-retry"><RefreshCw size={14} /> Try again</button>}</div>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="flex min-h-[220px] flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-card px-5 text-center"><div className="mb-3 rounded-xl bg-secondary p-3 text-primary"><FileText size={21} /></div><p className="font-display text-lg font-bold">{title}</p><p className="mt-1 max-w-sm text-sm text-muted-foreground">{description}</p>{action}</div>; }
export function StatusPill({ status }: { status: string }) { const config: Record<string, { label: string; cls: string }> = { eligible: { label: 'Eligible', cls: 'bg-[#e6f5ee] text-[#23794e]' }, verified: { label: 'Verified', cls: 'bg-[#e6f5ee] text-[#23794e]' }, pending: { label: 'In review', cls: 'bg-[#fff4d8] text-[#9b6a00]' }, 'needs-action': { label: 'Action needed', cls: 'bg-[#fff0e8] text-[#b65026]' }, 'in-review': { label: 'In review', cls: 'bg-[#eaf0ff] text-[#3c5da8]' }, submitted: { label: 'Submitted', cls: 'bg-[#eaf0ff] text-[#3c5da8]' }, approved: { label: 'Approved', cls: 'bg-[#e6f5ee] text-[#23794e]' }, ineligible: { label: 'Not eligible', cls: 'bg-[#fcebea] text-[#ae403b]' }, missing: { label: 'Missing', cls: 'bg-[#fcebea] text-[#ae403b]' } }; const item = config[status] || { label: status, cls: 'bg-secondary text-muted-foreground' }; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold ${item.cls}`} data-testid={`status-${status}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{item.label}</span>; }
export function ProgressBar({ value, color = 'bg-primary' }: { value: number; color?: string }) { return <div className="h-2 overflow-hidden rounded-full bg-secondary"><div className={`h-full rounded-full ${color} transition-[width] duration-500`} style={{ width: `${value}%` }} /></div>; }
export function SectionTitle({ title, action }: { title: string; action?: React.ReactNode }) { return <div className="mb-4 flex items-center justify-between"><h2 className="font-display text-[18px] font-extrabold tracking-[-.025em]">{title}</h2>{action}</div>; }
export function PrimaryButton({ children, onClick, type = 'button', disabled = false, className = '' }: { children: ReactNode; onClick?: () => void; type?: 'button' | 'submit'; disabled?: boolean; className?: string }) { return <button type={type} onClick={onClick} disabled={disabled} className={`inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-primary-foreground shadow-sm transition-transform hover:-translate-y-px disabled:cursor-not-allowed disabled:opacity-60 ${className}`} data-testid="button-primary">{children}</button>; }
export function MetricCard({ label, value, detail, icon: Icon, tint = 'bg-[#eef0ff] text-primary' }: { label: string; value: string | number; detail: string; icon: ElementType; tint?: string }) { return <div className="rounded-2xl border border-border bg-card p-5 shadow-[0_5px_20px_hsl(226_40%_30%_/.035)]"><div className="mb-5 flex items-start justify-between"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-muted-foreground">{label}</p><span className={`rounded-lg p-2 ${tint}`}><Icon size={16} /></span></div><p className="font-display text-[29px] font-extrabold tracking-[-.05em]" data-testid={`metric-${label.toLowerCase().replaceAll(' ', '-')}`}>{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></div>; }
export function ApplicationStepper({ steps }: { steps: { label: string; status: string; timestamp?: string | null }[] }) { return <div className="flex items-start">{steps.map((step, index) => <div key={`${step.label}-${index}`} className="relative flex flex-1 flex-col items-center text-center">{index < steps.length - 1 && <div className={`absolute left-1/2 top-3 h-px w-full ${step.status === 'complete' ? 'bg-[#4fa878]' : 'bg-border'}`} />}<div className={`relative z-10 flex h-6 w-6 items-center justify-center rounded-full border-2 ${step.status === 'complete' ? 'border-[#4fa878] bg-[#4fa878] text-white' : step.status === 'current' ? 'border-primary bg-card text-primary' : 'border-border bg-card text-transparent'}`}>{step.status === 'complete' ? <Check size={12} /> : <span className="h-1.5 w-1.5 rounded-full bg-current" />}</div><p className={`mt-2 max-w-[90px] text-[10px] leading-4 ${step.status === 'current' ? 'font-bold text-primary' : 'text-muted-foreground'}`}>{step.label}</p></div>)}</div>; }
export function ServiceIcon({ accent = 'indigo', icon: Icon = Sparkles }: { accent?: string; icon?: ElementType }) { const colors: Record<string, string> = { indigo: 'bg-[#eef0ff] text-[#4e5fc2]', mint: 'bg-[#e7f5ef] text-[#25805a]', amber: 'bg-[#fff4d9] text-[#9c6c08]', coral: 'bg-[#fff0e9] text-[#b95b35]', sky: 'bg-[#e5f3f7] text-[#26788a]' }; return <span className={`flex h-10 w-10 items-center justify-center rounded-xl ${colors[accent] || colors.indigo}`}><Icon size={18} /></span>; }